### PR TITLE
Add sponsor logos on home page for 2013

### PR DESCRIPTION
**Pull request by dexterous**

### CODE REVIEW

**Comment by dexterous** [comment]
@arpancj, I tried to keep to the CSS classes you had in there; feel free to change where you deem fit.

**Comment by dexterous** [comment]
Damn, just realized that this doesn't respond well to landscape mode on small screens. Will try to figure that out sometime today.

**Comment by dexterous** [comment]
Also, @arpancj, don't merge this in yet. We still have a few more sponsor confirmations to come in.

**Comment by arpancj** [comment]
> Damn, just realized that this doesn't respond well to landscape mode on
> small screens. Will try to figure that out sometime today.

Don't worry about the layout. I'll pull the changes, merge them and fix the
layout before pushing.

> Also, @arpancj https://github.com/arpancj, don't merge this in yet. We
> still have a few more sponsor confirmations to come in.

Sure, no problem. I'll wait.

I'll be off for 3 days for Good Friday and Easter. Will work on it after my
leave.

Regards,
Arpan

**Pull request merged**
