### PR TITLE
Update Josh Software logo; new BW logo

### PR DESCRIPTION
**Pull request by dexterous**

### CODE REVIEW

**Comment by arpancj** [comment]
@dexterous I've updated the sponsor layout. The color logo looks better.

**Comment by dexterous** [comment]
Saw that, agreed. Although, I'm not very enthusiastic about the individual
backgrounds for each logo.

**Comment by arpancj** [comment]
Had to use individual backgrounds for the logos, since some logos are white, some are gray and some are black. So decided to go with three background options for the logos.

**Comment by dexterous** [comment]
I realize that, but we an ask sponsors for alternate artwork. In fact, I
have the alternates for a few and I'll send in a PR with them added in.

**Pull request closed without merging**
